// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXvC80Mcv4AsMSb1rA6HOANGZjxlyJCQ',
    appId: '1:769254802844:web:124c6768abe857dde8f459',
    messagingSenderId: '769254802844',
    projectId: 'campus-recrutment',
    authDomain: 'campus-recrutment.firebaseapp.com',
    storageBucket: 'campus-recrutment.appspot.com',
    measurementId: 'G-2Z42SD8VT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9xUMdLQm6dh4TKgcF4yeaqd4DQ1Su-A',
    appId: '1:769254802844:android:b610f6945be0622ee8f459',
    messagingSenderId: '769254802844',
    projectId: 'campus-recrutment',
    storageBucket: 'campus-recrutment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhW_HhSYWaQkx4niNorgNoKuFtY03vfcc',
    appId: '1:769254802844:ios:fe439c59f94ebce1e8f459',
    messagingSenderId: '769254802844',
    projectId: 'campus-recrutment',
    storageBucket: 'campus-recrutment.appspot.com',
    iosBundleId: 'com.example.campusRecruitmentAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhW_HhSYWaQkx4niNorgNoKuFtY03vfcc',
    appId: '1:769254802844:ios:fe439c59f94ebce1e8f459',
    messagingSenderId: '769254802844',
    projectId: 'campus-recrutment',
    storageBucket: 'campus-recrutment.appspot.com',
    iosBundleId: 'com.example.campusRecruitmentAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgXvC80Mcv4AsMSb1rA6HOANGZjxlyJCQ',
    appId: '1:769254802844:web:6b4c23a06d18e24be8f459',
    messagingSenderId: '769254802844',
    projectId: 'campus-recrutment',
    authDomain: 'campus-recrutment.firebaseapp.com',
    storageBucket: 'campus-recrutment.appspot.com',
    measurementId: 'G-0VL0LNWVNW',
  );
}
